//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingLots
    {
        public ParkingLots()
        {
            this.ParkingAssignments = new HashSet<ParkingAssignments>();
            this.Vehicles = new HashSet<Vehicles>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int regular_capacity { get; set; }
        public int motorcycle_capacity { get; set; }
        public int special_capacity { get; set; }
    
        public virtual ICollection<ParkingAssignments> ParkingAssignments { get; set; }
        public virtual ICollection<Vehicles> Vehicles { get; set; }
    }
}
