//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicles
    {
        public Vehicles()
        {
            this.MovementLog = new HashSet<MovementLog>();
        }
    
        public int id { get; set; }
        public string brand { get; set; }
        public string color { get; set; }
        public string license_plate { get; set; }
        public string vehicle_type { get; set; }
        public int owner_id { get; set; }
        public Nullable<bool> uses_special_space { get; set; }
        public string is_active { get; set; }
        public bool is_parked { get; set; }
        public Nullable<int> ParkingLotId { get; set; }
    
        public virtual ICollection<MovementLog> MovementLog { get; set; }
        public virtual ParkingLots ParkingLots { get; set; }
        public virtual Users Users { get; set; }
    }
}
